#if WITH_GAME
#if PLATFORM_32BITS
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
namespace UnrealEngine
{
	public partial class UEdGraphPin_Deprecated
	{
		static readonly int PinName__Offset;
		public FString PinName
		{
			get{ CheckIsValid();return (FString)Marshal.PtrToStructure(_this.Get()+PinName__Offset, typeof(FString));}
			
		}
		
		static readonly int PinToolTip__Offset;
		public FString PinToolTip
		{
			get{ CheckIsValid();return (FString)Marshal.PtrToStructure(_this.Get()+PinToolTip__Offset, typeof(FString));}
			
		}
		
		static readonly int Direction__Offset;
		public EEdGraphPinDirection Direction
		{
			get{ CheckIsValid();return (EEdGraphPinDirection)Marshal.PtrToStructure(_this.Get()+Direction__Offset, typeof(EEdGraphPinDirection));}
			
		}
		
		static readonly int PinType__Offset;
		public FEdGraphPinType PinType
		{
			get{ CheckIsValid();return (FEdGraphPinType)Marshal.PtrToStructure(_this.Get()+PinType__Offset, typeof(FEdGraphPinType));}
			
		}
		
		static readonly int DefaultValue__Offset;
		public FString DefaultValue
		{
			get{ CheckIsValid();return (FString)Marshal.PtrToStructure(_this.Get()+DefaultValue__Offset, typeof(FString));}
			
		}
		
		static readonly int AutogeneratedDefaultValue__Offset;
		public FString AutogeneratedDefaultValue
		{
			get{ CheckIsValid();return (FString)Marshal.PtrToStructure(_this.Get()+AutogeneratedDefaultValue__Offset, typeof(FString));}
			
		}
		
		static readonly int DefaultObject__Offset;
		public UObject DefaultObject
		{
			get{ CheckIsValid(); IntPtr v = Marshal.ReadIntPtr(_this.Get() + DefaultObject__Offset); if (v == IntPtr.Zero)return null; UObject retValue = new UObject(); retValue._this = v; return retValue; }
			
		}
		
		static readonly int DefaultTextValue__Offset;
		public string DefaultTextValue
		{
			get{ CheckIsValid(); return ((FText)Marshal.PtrToStructure(_this.Get()+DefaultTextValue__Offset, typeof(FText))).ToString();}
			
		}
		
		static readonly int LinkedTo__Offset;
		public TObjectArray<UEdGraphPin_Deprecated>  LinkedTo
		{
					get{ CheckIsValid();return new TObjectArray<UEdGraphPin_Deprecated>((FScriptArray)Marshal.PtrToStructure(_this.Get()+LinkedTo__Offset, typeof(FScriptArray)));}
					set{ CheckIsValid();Marshal.StructureToPtr(value.InterArray, _this.Get()+LinkedTo__Offset, false);}
			
		}
		
		static readonly int SubPins__Offset;
		public TObjectArray<UEdGraphPin_Deprecated>  SubPins
		{
					get{ CheckIsValid();return new TObjectArray<UEdGraphPin_Deprecated>((FScriptArray)Marshal.PtrToStructure(_this.Get()+SubPins__Offset, typeof(FScriptArray)));}
					set{ CheckIsValid();Marshal.StructureToPtr(value.InterArray, _this.Get()+SubPins__Offset, false);}
			
		}
		
		static readonly int ParentPin__Offset;
		public UEdGraphPin_Deprecated ParentPin
		{
			get{ CheckIsValid(); IntPtr v = Marshal.ReadIntPtr(_this.Get() + ParentPin__Offset); if (v == IntPtr.Zero)return null; UEdGraphPin_Deprecated retValue = new UEdGraphPin_Deprecated(); retValue._this = v; return retValue; }
			
		}
		
		static readonly int ReferencePassThroughConnection__Offset;
		public UEdGraphPin_Deprecated ReferencePassThroughConnection
		{
			get{ CheckIsValid(); IntPtr v = Marshal.ReadIntPtr(_this.Get() + ReferencePassThroughConnection__Offset); if (v == IntPtr.Zero)return null; UEdGraphPin_Deprecated retValue = new UEdGraphPin_Deprecated(); retValue._this = v; return retValue; }
			
		}
		
		static UEdGraphPin_Deprecated()
		{
			IntPtr NativeClassPtr=GetNativeClassFromName("EdGraphPin_Deprecated");
			PinName__Offset=GetPropertyOffset(NativeClassPtr,"PinName");
			PinToolTip__Offset=GetPropertyOffset(NativeClassPtr,"PinToolTip");
			Direction__Offset=GetPropertyOffset(NativeClassPtr,"Direction");
			PinType__Offset=GetPropertyOffset(NativeClassPtr,"PinType");
			DefaultValue__Offset=GetPropertyOffset(NativeClassPtr,"DefaultValue");
			AutogeneratedDefaultValue__Offset=GetPropertyOffset(NativeClassPtr,"AutogeneratedDefaultValue");
			DefaultObject__Offset=GetPropertyOffset(NativeClassPtr,"DefaultObject");
			DefaultTextValue__Offset=GetPropertyOffset(NativeClassPtr,"DefaultTextValue");
			LinkedTo__Offset=GetPropertyOffset(NativeClassPtr,"LinkedTo");
			SubPins__Offset=GetPropertyOffset(NativeClassPtr,"SubPins");
			ParentPin__Offset=GetPropertyOffset(NativeClassPtr,"ParentPin");
			ReferencePassThroughConnection__Offset=GetPropertyOffset(NativeClassPtr,"ReferencePassThroughConnection");
			
		}
		
	}
	
}
#endif
#endif
