using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
namespace UnrealEngine
{
	/// <summary>Event type</summary>
	public enum EParticleEventType:byte
	{
		/// <summary>Any - allow any event</summary>
		EPET_Any=0,
		/// <summary>Spawn - a particle spawn event</summary>
		EPET_Spawn=1,
		/// <summary>Death - a particle death event</summary>
		EPET_Death=2,
		/// <summary>Collision - a particle collision event</summary>
		EPET_Collision=3,
		/// <summary>Burst - a particle burst event</summary>
		EPET_Burst=4,
		/// <summary>Blueprint - an event generated by level script</summary>
		EPET_Blueprint=5,
		EPET_MAX=6,
		
	}
	
}
