using System;
namespace UnrealEngine
{
	/// <summary>Struct that stores information about a function input which is needed to maintain connections and implement the function call.</summary>
	public partial struct FFunctionExpressionInput
	{
		/// <summary>
		/// Reference to the FunctionInput in the material function.
		/// This is a reference to a private object so it can't be saved, and must be generated by UpdateFromFunctionResource or SetMaterialFunction.
		/// </summary>
		public UMaterialExpressionFunctionInput ExpressionInput;
		/// <summary>Id of the FunctionInput, used to link ExpressionInput.</summary>
		public FGuid ExpressionInputId;
		/// <summary>Actual input struct which stores information about how this input is connected in the material.</summary>
		public FExpressionInput Input;
		
	}
	
}
