using System;
namespace UnrealEngine
{
	/// <summary>Struct that stores information about a function output which is needed to maintain connections and implement the function call.</summary>
	public partial struct FFunctionExpressionOutput
	{
		/// <summary>
		/// Reference to the FunctionOutput in the material function.
		/// This is a reference to a private object so it can't be saved, and must be generated by UpdateFromFunctionResource or SetMaterialFunction.
		/// </summary>
		public UMaterialExpressionFunctionOutput ExpressionOutput;
		/// <summary>Id of the FunctionOutput, used to link ExpressionOutput.</summary>
		public FGuid ExpressionOutputId;
		/// <summary>Actual output struct which stores information about how this output is connected in the material.</summary>
		public FExpressionOutput Output;
		
	}
	
}
