using System;
namespace UnrealEngine
{
	public partial class UBlueprintCore:UObject
	{
		/// <summary>
		/// Pointer to the skeleton class; this is regenerated any time a member variable or function is added but
		///       is usually incomplete (no code or hidden autogenerated variables are added to it)
		/// </summary>
		public TSubclassOf<UObject>  SkeletonGeneratedClass;
		
		/// <summary>Pointer to the 'most recent' fully generated class</summary>
		public TSubclassOf<UObject>  GeneratedClass;
		
		/// <summary>BackCompat:  Whether or not we need to purge references in this blueprint to the skeleton generated during compile-on-load</summary>
		public bool bLegacyNeedToPurgeSkelRefs;
		
		/// <summary>BackCompat: Whether or not this blueprint's authoritative CDO data has been migrated from the SkeletonGeneratedClass CDO to the GeneratedClass CDO</summary>
		public bool bLegacyGeneratedClassIsAuthoritative;
		
		/// <summary>Blueprint Guid</summary>
		public FGuid BlueprintGuid;
		
		
	}
	
}
