#if WITH_EDITOR
#if PLATFORM_64BITS
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
namespace UnrealEngine
{
	/// <summary>
	/// ALevelScriptActor is the base class for classes generated by
	/// ULevelScriptBlueprints. ALevelScriptActor instances are hidden actors that
	/// exist within a level, and can execute level-wide logic (operating on specific
	/// actor instances within the level). The level-script's functionality is defined
	/// inside the ULevelScriptBlueprint itself (using the blueprint's node-based
	/// interface).
	/// @see AActor
	/// @see https://docs.unrealengine.com/latest/INT/Engine/Blueprints/UserGuide/Types/LevelBlueprint/index.html
	/// @see ULevelScriptBlueprint
	/// @see https://docs.unrealengine.com/latest/INT/Engine/Blueprints/index.html
	/// @see UBlueprint
	/// </summary>
	public partial class ALevelScriptActor
	{
		static readonly int bInputEnabled__Offset;
		public bool bInputEnabled
		{
			get{ CheckIsValid();return BoolWrap.Get(_this.Get(), bInputEnabled__Offset, 1, 0, 1, 1);}
			
		}
		
		static ALevelScriptActor()
		{
			IntPtr NativeClassPtr=GetNativeClassFromName("LevelScriptActor");
			bInputEnabled__Offset=GetPropertyOffset(NativeClassPtr,"bInputEnabled");
			
		}
		
	}
	
}
#endif
#endif
