#if WITH_EDITOR
#if PLATFORM_64BITS
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
namespace UnrealEngine
{
	/// <summary>Struct that stores information about a function output which is needed to maintain connections and implement the function call.</summary>
	[StructLayout(LayoutKind.Explicit,Size=64)]
	public partial struct FFunctionExpressionOutput
	{
		/// <summary>
		/// Reference to the FunctionOutput in the material function.
		/// This is a reference to a private object so it can't be saved, and must be generated by UpdateFromFunctionResource or SetMaterialFunction.
		/// </summary>
		/// <summary>Id of the FunctionOutput, used to link ExpressionOutput.</summary>
		[FieldOffset(8)]
		public FGuid ExpressionOutputId;
		/// <summary>Actual output struct which stores information about how this output is connected in the material.</summary>
		[FieldOffset(24)]
		public FExpressionOutput Output;
		
	}
	
}
#endif
#endif
