#if WITH_EDITOR
#if PLATFORM_64BITS
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
namespace UnrealEngine
{
	/// <summary>Struct that stores information about a function input which is needed to maintain connections and implement the function call.</summary>
	[StructLayout(LayoutKind.Explicit,Size=88)]
	public partial struct FFunctionExpressionInput
	{
		/// <summary>
		/// Reference to the FunctionInput in the material function.
		/// This is a reference to a private object so it can't be saved, and must be generated by UpdateFromFunctionResource or SetMaterialFunction.
		/// </summary>
		/// <summary>Id of the FunctionInput, used to link ExpressionInput.</summary>
		[FieldOffset(8)]
		public FGuid ExpressionInputId;
		/// <summary>Actual input struct which stores information about how this input is connected in the material.</summary>
		[FieldOffset(24)]
		public FExpressionInput Input;
		
	}
	
}
#endif
#endif
