#if WITH_EDITOR
#if PLATFORM_64BITS
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
namespace UnrealEngine
{
	/// <summary>
	/// PawnNoiseEmitterComponent tracks noise event data used by SensingComponents to hear a Pawn.
	/// This component is intended to exist on either a Pawn or its Controller. It does nothing on network clients.
	/// </summary>
	public partial class UPawnNoiseEmitterComponent
	{
		static readonly int bAIPerceptionSystemCompatibilityMode__Offset;
		/// <summary>
		/// If set to true (default value) will notify AIPerceptionSystem about noise events
		/// otherwise only PawnSensingComponents will be able to pick up noises generated by this component
		/// </summary>
		public bool bAIPerceptionSystemCompatibilityMode
		{
			get{ CheckIsValid();return BoolWrap.Get(_this.Get(), bAIPerceptionSystemCompatibilityMode__Offset, 1, 0, 1, 1);}
			set{ CheckIsValid();BoolWrap.Set(value,_this.Get(), bAIPerceptionSystemCompatibilityMode__Offset, 1,0,1,1);}
			
		}
		
		static readonly int LastRemoteNoisePosition__Offset;
		/// <summary>Most recent noise made by this pawn not at its own location</summary>
		public FVector LastRemoteNoisePosition
		{
			get{ CheckIsValid();return (FVector)Marshal.PtrToStructure(_this.Get()+LastRemoteNoisePosition__Offset, typeof(FVector));}
			
		}
		
		static readonly int NoiseLifetime__Offset;
		/// <summary>After this amount of time, new sound events will overwrite previous sounds even if they are not louder (allows old sounds to decay)</summary>
		public float NoiseLifetime
		{
			get{ CheckIsValid();return (float)Marshal.PtrToStructure(_this.Get()+NoiseLifetime__Offset, typeof(float));}
			set{ CheckIsValid();Marshal.StructureToPtr(value, _this.Get()+NoiseLifetime__Offset, false);}
			
		}
		
		static readonly int LastRemoteNoiseVolume__Offset;
		/// <summary>Most recent volume of noise made by this pawn not at its own location</summary>
		public float LastRemoteNoiseVolume
		{
			get{ CheckIsValid();return (float)Marshal.PtrToStructure(_this.Get()+LastRemoteNoiseVolume__Offset, typeof(float));}
			
		}
		
		static readonly int LastRemoteNoiseTime__Offset;
		/// <summary>Time of last remote noise update</summary>
		public float LastRemoteNoiseTime
		{
			get{ CheckIsValid();return (float)Marshal.PtrToStructure(_this.Get()+LastRemoteNoiseTime__Offset, typeof(float));}
			
		}
		
		static readonly int LastLocalNoiseVolume__Offset;
		/// <summary>Most recent noise made by this pawn at its own location</summary>
		public float LastLocalNoiseVolume
		{
			get{ CheckIsValid();return (float)Marshal.PtrToStructure(_this.Get()+LastLocalNoiseVolume__Offset, typeof(float));}
			
		}
		
		static readonly int LastLocalNoiseTime__Offset;
		/// <summary>Time of last local noise update</summary>
		public float LastLocalNoiseTime
		{
			get{ CheckIsValid();return (float)Marshal.PtrToStructure(_this.Get()+LastLocalNoiseTime__Offset, typeof(float));}
			
		}
		
		static UPawnNoiseEmitterComponent()
		{
			IntPtr NativeClassPtr=GetNativeClassFromName("PawnNoiseEmitterComponent");
			bAIPerceptionSystemCompatibilityMode__Offset=GetPropertyOffset(NativeClassPtr,"bAIPerceptionSystemCompatibilityMode");
			LastRemoteNoisePosition__Offset=GetPropertyOffset(NativeClassPtr,"LastRemoteNoisePosition");
			NoiseLifetime__Offset=GetPropertyOffset(NativeClassPtr,"NoiseLifetime");
			LastRemoteNoiseVolume__Offset=GetPropertyOffset(NativeClassPtr,"LastRemoteNoiseVolume");
			LastRemoteNoiseTime__Offset=GetPropertyOffset(NativeClassPtr,"LastRemoteNoiseTime");
			LastLocalNoiseVolume__Offset=GetPropertyOffset(NativeClassPtr,"LastLocalNoiseVolume");
			LastLocalNoiseTime__Offset=GetPropertyOffset(NativeClassPtr,"LastLocalNoiseTime");
			
		}
		
	}
	
}
#endif
#endif
